version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - /etc/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "443:443"
    depends_on:
      - frontend
      - backend
